#!/bin/bash

usage() {
    echo "USAGE: l SEARCH_STRING"
}

if [ -z "$1" ]; then
    usage
    echo "ERROR: Search string not specified."
    exit 1
fi

if [ $# -ne 1 ]; then
    echo "ERROR: Can only accept one search string."
    usage
    exit 1
fi

GREEN='\e[32m'
NC='\033[0m'

for link in $(n $1 links |grep -i $1 | cut -d, -f2); do
    line=`n $1 links |grep $link`
    title=`echo $line |cut -d, -f 1 |cut -d: -f2`
    printf "${GREEN}${title}:${NC} "
    echo $link
done
